// 쉬라인 공방전 관련 패킷 정의
// 점령 상태를 전달하는 패킷, 쉬라인 포인트의 체력을 보내주는 패킷

#if !defined(AGPPSHRINEBATTLE_H)
#define AGPPSHRINEBATTLE_H

#include "AgpdShrineBattle.h"
#include "AgpmShrineBattle.h"

typedef enum _eAgpmShrineBattlePacketOperation
{
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION_REQUEST	= 0,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION_TOTAL,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_TIMEBAR_STATE,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_STATUS_UPDATE,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_TRYIMPRINT,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_IMPRINT_RESULT,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_MESSAGE_CODE,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_JOIN_REQUEST,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_JOIN_ANSWER,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_READY_TO_START,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_PVP_RECORD,
	AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_RACE_RECORD,
}eAgpmShrineBattlePacketOperation;


#pragma pack (1)

struct PACKET_AGPP_SHRINEBATTLE : public PACKET_HEADER
{
	CHAR FlagLow;
	INT16 nParam;
	INT32 nShrinePointID;

	PACKET_AGPP_SHRINEBATTLE() : nParam(0), FlagLow(1)
	{
		cType = AGPM_SHRINEBATTLE_PACKET_TYPE;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE);
		nShrinePointID = 0;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_INFORMATION_REQUEST : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nCid;

	PACKET_AGPP_SHRINEBATTLE_INFORMATION_REQUEST(INT32 Cid)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION_REQUEST;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_INFORMATION_REQUEST);

		nCid = Cid;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_INFORMATION : public PACKET_AGPP_SHRINEBATTLE
{
	AgpdShrinePoint stShrinePoint;

	PACKET_AGPP_SHRINEBATTLE_INFORMATION()
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_INFORMATION);
	}
};

struct PACKET_AGPP_SHRINEBATTLE_INFORMATION_TOTAL : public PACKET_AGPP_SHRINEBATTLE
{
	PACKET_AGPP_SHRINEBATTLE_INFORMATION m_stPointInformation[AGPDSHRINEBATTLE_MAX_SHRINE_POINT_NUMBER];

	PACKET_AGPP_SHRINEBATTLE_INFORMATION_TOTAL()
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_INFORMATION_TOTAL;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_INFORMATION_TOTAL);
	}
};

struct PACKET_AGPP_SHRINEBATTLE_TIMEBAR_STATE : public PACKET_AGPP_SHRINEBATTLE
{
	BOOL bAppear;

	PACKET_AGPP_SHRINEBATTLE_TIMEBAR_STATE(INT32 ShrinePointID, BOOL Appear)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_TIMEBAR_STATE;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_TIMEBAR_STATE);
		nShrinePointID = ShrinePointID;
		bAppear = Appear;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_STATUS_UPDATE : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nPrevStatus;
	AgpdShrinePoint stShrinePoint;
	PACKET_AGPP_SHRINEBATTLE_STATUS_UPDATE(INT32 PrevStatus, AgpdShrinePoint ShrinePoint)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_STATUS_UPDATE;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_STATUS_UPDATE);

		nPrevStatus = PrevStatus;
		stShrinePoint = ShrinePoint;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_TRYIMPRINT : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nCid;
	PACKET_AGPP_SHRINEBATTLE_TRYIMPRINT(INT32 Cid, INT32 ShrinePointID)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_TRYIMPRINT;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_TRYIMPRINT);

		nCid = Cid;
		nShrinePointID = ShrinePointID;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_IMPRINT_RESULT : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nCid;
	BOOL bResult;
	INT32 nPrevStatus;
	INT32 nShrineObjectCID;

	PACKET_AGPP_SHRINEBATTLE_IMPRINT_RESULT(INT32 Cid, INT32 ShrinePointID, INT32 PrevStatus, BOOL ImprintResult, INT32 ShrineObjectCID)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_IMPRINT_RESULT;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_IMPRINT_RESULT);

		nCid = Cid;
		nShrinePointID = ShrinePointID;
		bResult = ImprintResult;
		nPrevStatus = PrevStatus;
		nShrineObjectCID = ShrineObjectCID;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_MESSAGE_CODE : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 eMessageCode;
	INT32 nRaceID;
	CHAR  szPointCharacterName[AGPDCHARACTER_MAX_ID_LENGTH + 1];

	PACKET_AGPP_SHRINEBATTLE_MESSAGE_CODE(INT32 MessageCode, INT32 ShrinePointID, INT32 RaceID)
	{
		nParam = AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_MESSAGE_CODE;
		unPacketLength = (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_MESSAGE_CODE);

		nRaceID = RaceID;
		nShrinePointID = ShrinePointID;
		eMessageCode = MessageCode;

		memset(szPointCharacterName, 0, AGPDCHARACTER_MAX_ID_LENGTH + 1);
	}
};

/************************************************************************/
/* Global Renewel                                                       */
/************************************************************************/

struct PACKET_AGPP_SHRINEBATTLE_JOIN_REQUEST : public PACKET_AGPP_SHRINEBATTLE
{
	PACKET_AGPP_SHRINEBATTLE_JOIN_REQUEST(INT32 ShrinePointID)
	{
		nParam			= AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_JOIN_REQUEST;
		unPacketLength	= (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_JOIN_REQUEST);

		nShrinePointID	= ShrinePointID;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_JOIN_ANSWER : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nCID;

	PACKET_AGPP_SHRINEBATTLE_JOIN_ANSWER(INT32 CID, INT32 ShrinePointID)
	{
		nParam			= AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_JOIN_ANSWER;
		unPacketLength	= (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_JOIN_ANSWER);

		nCID			= CID;
		nShrinePointID	= ShrinePointID;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_READY_TO_OPEN : public PACKET_AGPP_SHRINEBATTLE
{
	INT32 nRestMinute;

	PACKET_AGPP_SHRINEBATTLE_READY_TO_OPEN(INT32 RestMinute, INT32 ShrinePointID)
	{
		nParam			= AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_READY_TO_START;
		unPacketLength	= (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_READY_TO_OPEN);

		nRestMinute		= RestMinute;
		nShrinePointID	= ShrinePointID;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_SCORE : public PACKET_AGPP_SHRINEBATTLE
{
	INT32	m_lWin;
	INT32	m_lLose;

	PACKET_AGPP_SHRINEBATTLE_SCORE(INT32& lWin, INT32& lLose)
	{
		nParam			= AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_PVP_RECORD;
		unPacketLength	= (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_SCORE);

		m_lWin			= lWin;
		m_lLose			= lLose;
	}
};

struct PACKET_AGPP_SHRINEBATTLE_RACE_SCORE : public PACKET_AGPP_SHRINEBATTLE
{
	INT32	m_lWin;
	INT32	m_lLose;

	PACKET_AGPP_SHRINEBATTLE_RACE_SCORE(INT32& lWin, INT32& lLose)
	{
		nParam			= AGPMSHRINEBATTLE_PACKET_SHRINEPOINT_RACE_RECORD;
		unPacketLength	= (UINT16)sizeof(PACKET_AGPP_SHRINEBATTLE_RACE_SCORE);

		m_lWin			= lWin;
		m_lLose			= lLose;
	}
};

#pragma pack ()


#endif